
import { getPortfolioData } from "@/lib/data";
import { Card, CardContent } from "@/components/ui/card";
import { CheckCircle } from "lucide-react";

// This page is statically generated by default as it doesn't use dynamic functions.

export default async function SkillsPage() {
  const { skills, tools } = await getPortfolioData();

  return (
    <>
      {/* Skills Section */}
      <section id="skills" className="bg-background py-24 sm:py-32">
        <div className="container">
          <div className="text-center">
            <h2 className="font-headline text-4xl font-semibold text-primary sm:text-5xl">
              Keahlian Utama
            </h2>
            <div className="mx-auto mt-2 h-1.5 w-24 bg-primary" />
          </div>
          <div className="mt-16 flex flex-wrap justify-center gap-4">
            {skills.map((skill, index) => (
              <div key={`${skill}-${index}`} className="rounded-lg bg-foreground px-5 py-2.5 font-medium text-primary shadow-md dark:bg-card">
                {skill}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Tools Section */}
      <section id="tools" className="bg-secondary py-24 sm:py-32">
        <div className="container">
          <div className="text-center">
            <h2 className="font-headline text-4xl font-semibold text-primary sm:text-5xl">
              Tools yang Digunakan
            </h2>
            <p className="mt-4 text-lg text-foreground/70 max-w-2xl mx-auto">
              Beberapa tools yang saya kuasai untuk mendukung analisis dan strategi digital marketing.
            </p>
          </div>
          <Card className="mt-16 max-w-3xl mx-auto bg-card">
            <CardContent className="p-8">
              <ul className="grid grid-cols-2 gap-x-8 gap-y-4 md:grid-cols-3">
                {tools.map((tool, index) => (
                  <li key={`${tool}-${index}`} className="flex items-center gap-3">
                    <CheckCircle className="h-5 w-5 text-accent flex-shrink-0" />
                    <span className="text-foreground/80">{tool}</span>
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>
        </div>
      </section>
    </>
  );
}
